version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: f863b492973b_WatchHumansDB
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "WatchHumans!"
      POSTGRES_DB: watchhumans
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:WatchHumans!@db:5432/watchhumans"
    networks:
      - app_network
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/main

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
